name: 'camel_install'
description: 'Setup python environment and install dependencies for CAMEL using uv.'
inputs:
  python-version:
    description: 'Python version.'
    required: true
    default: '3.10'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '${{ inputs.python-version }}'
    - name: Install uv
      run: |
        pip install uv
      shell: bash
    - uses: actions/cache/restore@v3
      id: cache-restore
      name: Restore caches for the virtual environment based on uv.lock
      with:
        path: ./.venv
        key: venv-${{ hashFiles('uv.lock') }}
    - name: Verify and setup virtual environment
      id: verify-venv
      run: |
        # Check if Python exists and is executable in the venv
        if [ -f ".venv/bin/python" ] && [ -x ".venv/bin/python" ] && ".venv/bin/python" --version > /dev/null 2>&1; then
          echo "Virtual environment exists and seems valid"
          echo "recreated=false" >> $GITHUB_OUTPUT
        else
          echo "Virtual environment invalid or incomplete, recreating..."
          rm -rf .venv
          uv venv .venv --python=${{ inputs.python-version }}
          
          # Verify the newly created venv
          if [ -f ".venv/bin/python" ] && [ -x ".venv/bin/python" ] && ".venv/bin/python" --version > /dev/null 2>&1; then
            echo "Successfully created virtual environment"
          else
            echo "Failed to create a valid virtual environment"
            exit 1
          fi
          echo "recreated=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Install the project dependencies
      run: |
        source .venv/bin/activate
        uv pip install -e ".[all, dev, docs]"
      shell: bash
    - uses: actions/cache/save@v3
      name: Save caches based on uv.lock
      if: ${{ !steps.cache-restore.outputs.cache-hit || steps.verify-venv.outputs.recreated == 'true' }}
      with:
        path: ./.venv
        key: venv-${{ hashFiles('uv.lock') }}
